#!/bin/bash
index=4
greeting="Hello" 			#no spaces
if [ $index -lt 5 ]			#-lt = bash operator - see below; mind the spaces of the if conditions
then
  echo $index				#use $ to access a variable's value
else
  echo 5
fi

#bash numeric operators:
-lt 	<
-eq 	=
-ne		!=
-le		<=
-ge		>=
-gt 	>
-z 		is null
#bash string comparison:
"$foo" == "$bar"

for word in $paragraph
do
  echo $word
done
#single line possible:
for i in *.fasta; do j="${i%.*}" && whatever -with $i $j.out; done

#while and until loops are similar in function
while [ $index -lt 5 ]
do
  echo $index
  index=$((index + 1))		#note this syntax for arithmetic operations
done


read number 				#reads standard input into variable "number"
for color in "$@"			#runs indefinitely
saycolors.sh red green blue	#position-based inputs
files=/some/directory/*		#file access for data, list all files in the dir
for file in $files
do
  echo $file
done